spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/
zuul:
  prefix: /coupon
  routes:
    # 优惠券模板微服务路由配置定义
    template:
      path: /coupon-service/**
      serviceId: coupon-service
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000
---
spring:
  profiles: dev
server:
  port: 8060

---
spring:
  profiles: test
server:
  port: 8061

---
spring:
  profiles: prod
server:
  port: 8062